import { ItemStatus, ItemType } from '@prisma/client';

export class Item {
  constructor(
    public readonly id: string,
    public readonly title: string,
    public readonly description: string,
    public readonly status: ItemStatus,
    public readonly type: ItemType,
    public readonly location: string,
    public readonly lostFoundAt: Date,
    public readonly userId: string,
    public readonly categoryId: string | null,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date,
    public readonly isActive?: boolean,
    public readonly isModerated?: boolean,
    public readonly isDeleted?: boolean,
    public readonly priority?: number,
    public readonly viewCount?: number,
    public readonly attributes?: any | null,
    public readonly latitude?: number | null,
    public readonly longitude?: number | null,
    public readonly radius?: number | null,
    public readonly color?: string | null,
    public readonly brand?: string | null,
    public readonly size?: string | null,
    public readonly material?: string | null,
    public readonly expiresAt?: Date | null,
  ) {}

  static create(
    title: string,
    description: string,
    status: ItemStatus,
    type: ItemType,
    location: string,
    lostFoundAt: Date,
    userId: string,
    categoryId: string,
    attributes?: any | null,
    latitude?: number | null,
    longitude?: number | null,
    radius?: number | null,
    color?: string | null,
    brand?: string | null,
    size?: string | null,
    material?: string | null,
    expiresAt?: Date | null,
  ): Item {
    return new Item(
      crypto.randomUUID(),
      title,
      description,
      status,
      type,
      location,
      lostFoundAt,
      userId,
      categoryId,
      new Date(),
      new Date(),
      true,
      false,
      false,
      1,
      0,
      attributes,
      latitude,
      longitude,
      radius,
      color,
      brand,
      size,
      material,
      expiresAt,
    );
  }
}
